#!/bin/bash
# FILE : bbflip.sh
# Function: Flips all images in a directory upside down. Creates mirror image Top-Bottom.
# Copyright (C) 2006 Dave Crouse <dave NOSPAMat usalug.org>
# ------------------------------------------------------------------------ #
if [[ -z $( type -p convert ) ]]; then echo -e "ImageMagick -- NOT INSTALLED !";exit ;fi

export IFS=$'\n';
for i in $(find . -maxdepth 1 -type f -iname "*.jpg");
do
echo "Flipping ${i:2}" # Comment out this line to remove output text.
convert -flip ${i:2} new_${i:2}; mv new_${i:2} ${i:2}
done
exit 0