#!/bin/bash
# FILE : bbindex.sh
# Function: Creates a visual index of all the jpegs in the directory..
# Note, Only creates index of .jpg does NOT include .JPG at this time.
# Copyright (C) 2006 Dave Crouse <dave NOSPAMat usalug.org>
# ------------------------------------------------------------------------ #
if [[ -z $( type -p convert ) ]]; then echo -e "ImageMagick -- NOT INSTALLED !";exit ;fi

export IFS=$'\n';
convert vid:*.jpg INDEX.jpg;
exit 0
