#!/bin/bash
# FILE : bbrecom.sh
# Function: Reads all the comments of all images in the directory.
# Copyright (C) 2006 Dave Crouse <dave NOSPAMat usalug.org>
# ------------------------------------------------------------------------ #
if [[ -z $( type -p rdjpgcom ) ]]; then echo -e "The program rdjpgcom -- NOT INSTALLED !";exit ;fi

export IFS=$'\n';
for i in $(find . -maxdepth 1 -type f -iname "*.jpg");
do
echo "Comments for ${i:2}" >> /tmp/bbrecom; echo "-----------" >> /tmp/bbrecom; rdjpgcom ${i:2} >> /tmp/bbrecom; echo "-----------" >> /tmp/bbrecom; 
echo "" >> /tmp/bbrecom; echo "" >> /tmp/bbrecom; 
done
less /tmp/bbrecom ; rm -f /tmp/bbrecom
exit 0