#!/bin/bash
# FILE : bbrotate.sh
# Function: Rotate all images in a directory. Specify clockwise rotation.
# Copyright (C) 2006 Dave Crouse <dave NOSPAMat usalug.org>
# ------------------------------------------------------------------------ #
if [[ -z $( type -p convert ) ]]; then echo -e "ImageMagick -- NOT INSTALLED !";exit ;fi
    
if [[ -z "$1" || $1 = *[^0-9]* ]] ; then
	echo " ";
	echo "		######### COMMAND FAILED ########## ";
	echo "		USAGE: $0 rotationindegrees";
	echo "		EXAMPLE: $0 90";
	echo "		This would rotate images 90 degrees clockwise.";
	echo "		Note: rotation variable MUST be numeric ! ";
	echo "		######### COMMAND FAILED ########## ";echo " ";
else

export IFS=$'\n';
for i in $(find . -maxdepth 1 -type f -iname "*.jpg");
do
echo "Rotating ${i:2} $1 degrees." ;convert -rotate $1 ${i:2} new_${i:2}; mv new_${i:2} ${i:2} ;
done
fi
exit 0
