#!/bin/bash
# FILE : bbsolarize.sh
# Function: "solorizes" all images in the directory.
# 	    Produces a solarization effect as seen when exposing a photographic 
#           film to light during  the development process.
# Copyright (C) 2006 Dave Crouse <dave NOSPAMat usalug.org>
# ------------------------------------------------------------------------ #
if [[ -z $( type -p convert ) ]]; then echo -e "ImageMagick -- NOT INSTALLED !";exit ;fi

if [ -z "$1" ] ; then
	echo " ";
	echo "		######### COMMAND FAILED ########## ";
	echo "		USAGE: $0 intensity_number";
	echo "		EXAMPLE: $0 50";
	echo "		intensity (0 - 99.9) 0 being the most, 99.9 the least. ";
	echo "		######### COMMAND FAILED ########## ";echo " ";
else

export IFS=$'\n';
for i in $(find . -maxdepth 1 -type f -iname "*.jpg");
do 
convert -solarize ${1}% ${i:2} _${i:2};
mv _${i:2} ${i:2}
echo "Solarized image ${i:2}";
done
fi
exit 0