#!/bin/bash

# bc term window,   I changed it to nano as a test and it works DK
# starts or activates bc calculator in urxvt window in the middle of the screen
# set program to run here, I have bc (a calculator) and nano installed and both work DK
# prog=nano
prog=bc
# configurable variables
sleep="0.01"             # sleep before it gets active
width="800"                 # window width
height="300"                 # window height

# checks
command -v xdpyinfo >/dev/null 2>&1 ||    { >&2 echo "I need xdpyinfo." ; exit 1; }
command -v xdotool >/dev/null 2>&1 ||   { >&2 echo "I need xdotool." ; exit 1; }
command -v awk >/dev/null 2>&1 ||   { >&2 echo "I need awk." ; exit 1; }
command -v bc >/dev/null 2>&1 ||   { >&2 echo "I need bc." ; exit 1; }

# get screen resolution width/height and halve it
read -r w h <<<$(xdpyinfo | awk -F'[ x]+' '/dimensions:/{print $3, $4}')
halfw=$((w / 2))
halfh=$((h / 2))

# calc stuff
centerw=$((halfw - ww / 2))
centerh=$((halfh - wh / 2))

# action
# check if one is allready active and select and exit
xdotool search -name 'calculator' windowactivate && { echo "allready running" ; exit; }

# if not launch one
# 
(urxvt -title calculator -bg black -e $prog -l -q & sleep "$sleep") && xdotool search --sync --name 'calculator' windowactivate windowsize "$width" "$height" windowmove "$centerw" "$centerh"  
