#!/bin/bash
# got from gotbletu, runs bleachbit and cleans the below, I took some out DK
#	http://bleachbit.sourceforge.net/documentation/command-line
#	dont delete pidgin, vim, transmission, thumbnails, bash, system, deep
# cdusr/bin/
bleachbit -c \
chromium.cache \
chromium.cookies \
chromium.current_session \
chromium.dom \
chromium.form_history \
chromium.history \
chromium.passwords \
chromium.search_engines \
chromium.vacuum \
elinks.history \
filezilla.mru \
firefox.cache \
firefox.cookies \
firefox.crash_reports \
firefox.dom \
firefox.download_history \
firefox.forms \
firefox.passwords \
firefox.session_restore \
firefox.site_preferences \
firefox.url_history \
firefox.vacuum \
flash.cache \
flash.cookies \
gimp.tmp \
gnome.search_history \
google_chrome.cache \
google_chrome.cookies \
google_chrome.dom \
google_chrome.form_history \
google_chrome.history \
google_chrome.passwords \
google_chrome.search_engines \
google_chrome.session \
google_chrome.vacuum \
google_earth.temporary_files \
google_toolbar.search_history \
gwenview.recent_documents \
java.cache \
kde.cache \
kde.recent_documents \
kde.tmp \
konqueror.cookies \
konqueror.current_session \
konqueror.url_history \
libreoffice.cache \
libreoffice.history \
liferea.cache \
liferea.cookies \
liferea.vacuum \
links2.history \
midnightcommander.history \
miro.cache \
miro.logs \
nautilus.history \
openofficeorg.cache \
openofficeorg.recent_documents \
opera.cache \
opera.cookies \
opera.current_session \
opera.dom \
opera.download_history \
opera.search_history \
opera.url_history \
paint.mru \
skype.chat_logs \
sqlite3.history \
system.cache \
system.clipboard \
system.custom \
system.desktop_entry \
system.free_disk_space \
system.localizations \
system.memory \
system.recent_documents \
system.rotated_logs \
system.tmp \
system.trash \
vlc.mru \
vuze.backup_files \
vuze.cache \
vuze.logs \
vuze.tmp \
wine.tmp \
winetricks.temporary_files \
x11.debug_logs \
xchat.logs \
xine.cache \
