#!/usr/bin/env bash
cmd="dmenu -i -l 10 -fn Ubuntu-12:normal -nf #babdb6 -nb #75507b -sf #000000 -sb #d3d7cf"

while [ -z "$engine" ]; do
engine=$(sr -elvi | gawk '{if (NR!=1) { print $1 }}' | $cmd -p "Where?") || exit
done

while [ -z "$query" ]; do
query=$(echo "" | $cmd -p "Searching $engine") || exit
done

sr "$engine" "$query"
