#!/bin/bash
entry=`dmenu_path | dmenu -fn "-*-bitstream vera sans mono-medium-r-normal-*-10-*-*-*-*-*-*-*" -nb "#222222" -nf "#dcdccc"`
if test "X$entry" != "X"; then
        surfraw http://www.google.com/search?q="$entry"
fi
